Repository epitech-mirroring/R-Type-Reborn, pull requests merged in 2024-10, with the labels that each got.

#11 :sparkles: Create EntityManager and simples entities for the server game logic (EPI-86/EPI-87/EPI-88)
  .clang-tidy
  .editorconfig
  CMakeLists.txt
  client/CMakeLists.txt
  client/main.cpp
  server/CMakeLists.txt
  server/Server.cpp
  server/Server.hpp
  server/entities/ABullet.cpp
  server/entities/ABullet.hpp
  server/entities/AEntity.cpp
  server/entities/AEntity.hpp
  server/entities/AShip.cpp
  server/entities/AShip.hpp
  server/entities/BasicEnemy.cpp
  server/entities/BasicEnemy.hpp
  server/entities/ClassicBullet.cpp
  server/entities/ClassicBullet.hpp
  server/entities/EntityManager.cpp
  server/entities/EntityManager.hpp
  server/entities/IEntity.hpp
  server/entities/Player.cpp
  server/entities/Player.hpp
  server/main.cpp
  src/CMakeLists.txt
Labels: enhancement

#7 :memo: Study of different architectures of the engine (EPI-19)
  documentation/benchmarks/game_engine/architecture_study.md
Labels: documentation

#12 :space_invader: Create server game logic
  .clang-tidy
  .gitignore
  CMakeLists.txt
  client/CMakeLists.txt
  conanfile.txt
  server/CMakeLists.txt
  server/GameLogic.cpp
  server/GameLogic.hpp
  server/Random.cpp
  server/Random.hpp
  server/entities/ABullet.cpp
  server/entities/ABullet.hpp
  server/entities/AEntity.cpp
  server/entities/AEntity.hpp
  server/entities/AShip.cpp
  server/entities/AShip.hpp
  server/entities/BasicEnemy.cpp
  server/entities/ClassicBullet.cpp
  server/entities/ClassicBullet.hpp
  server/entities/EntityManager.cpp
  server/entities/EntityManager.hpp
  server/entities/IEntity.hpp
  server/entities/Player.cpp
Labels: enhancement

#13 :sparkles: Add function to transform binary into value and vice versa
  .clang-tidy
  server/CMakeLists.txt
  server/utils/BinaryVector.cpp
  server/utils/BinaryVector.hpp
Labels: enhancement

#15 :sparkles: Add client dto (EPI-103)
  server/dto/APlayerDTO.cpp
  server/dto/APlayerDTO.hpp
  server/dto/DTORegistry.cpp
  server/dto/PlayerStartMoveDown.cpp
  server/dto/PlayerStartMoveDown.hpp
  server/dto/PlayerStartMoveLeft.cpp
  server/dto/PlayerStartMoveLeft.hpp
  server/dto/PlayerStartMoveRight.cpp
  server/dto/PlayerStartMoveRight.hpp
  server/dto/PlayerStartMoveUp.cpp
  server/dto/PlayerStartMoveUp.hpp
  server/dto/PlayerStartShoot.cpp
  server/dto/PlayerStartShoot.hpp
  server/dto/PlayerStopMoveDown.cpp
  server/dto/PlayerStopMoveDown.hpp
  server/dto/PlayerStopMoveLeft.cpp
  server/dto/PlayerStopMoveLeft.hpp
  server/dto/PlayerStopMoveRight.cpp
  server/dto/PlayerStopMoveRight.hpp
  server/dto/PlayerStopMoveUp.cpp
  server/dto/PlayerStopMoveUp.hpp
  server/dto/PlayerStopShoot.cpp
  server/dto/PlayerStopShoot.hpp
Labels: enhancement, network

#16 :bug: Fix forgotten DTO in CMakeLists (EPI-105)
  server/dto/CMakeLists.txt
  server/dto/DTORegistry.cpp
  server/dto/PlayerStartMoveDown.cpp
  server/dto/PlayerStartMoveDown.hpp
  server/dto/PlayerStartMoveLeft.cpp
  server/dto/PlayerStartMoveLeft.hpp
  server/dto/PlayerStartMoveRight.cpp
  server/dto/PlayerStartMoveRight.hpp
  server/dto/PlayerStartMoveUp.cpp
  server/dto/PlayerStartMoveUp.hpp
  server/dto/PlayerStartShoot.cpp
  server/dto/PlayerStartShoot.hpp
  server/dto/PlayerStopMoveDown.cpp
  server/dto/PlayerStopMoveLeft.cpp
  server/dto/PlayerStopMoveLeft.hpp
  server/dto/PlayerStopMoveRight.cpp
  server/dto/PlayerStopMoveRight.hpp
  server/dto/PlayerStopMoveUp.cpp
  server/dto/PlayerStopShoot.cpp
  server/dto/PlayerStopShoot.hpp
  server/dto/entity/AEntityDTO.cpp
  server/dto/entity/AEntityDTO.hpp
  server/dto/entity/EntityCreationDTO.cpp
  server/dto/entity/EntityCreationDTO.hpp
  server/dto/entity/EntityDeletionDTO.cpp
  server/dto/entity/EntityDeletionDTO.hpp
  server/dto/entity/EntityPositionDTO.cpp
  server/dto/entity/EntityPositionDTO.hpp
  server/dto/entity/EntityTypeEnum.hpp
  server/dto/player/APlayerDTO.cpp
  server/dto/player/APlayerDTO.hpp
  server/dto/player/PlayerActionEnum.hpp
  server/dto/player/PlayerActionStartDTO.cpp
  server/dto/player/PlayerActionStartDTO.hpp
  server/dto/player/PlayerActionStopDTO.cpp
  server/dto/player/PlayerActionStopDTO.hpp
Labels: bug

#18 :memo: Create documentation for developers (EPI-114)
  README.md
  documentation/developers/about.md
  documentation/developers/client/client.md
  documentation/developers/networking/networking.md
  documentation/developers/networking/protocole.md
  documentation/developers/networking/rfc.md
  documentation/developers/server/server.md
  documentation/developers/stellar_forge/stellar_forge.md
  documentation/guide/conan_installation_guide.md
  documentation/guide/vcpkg_installation_guide.md
Labels: documentation
